version: '3.8'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: danydodson/seesee-nginx
    ports:
      - '80:8081'
    env_file:
      - ./nginx/.env
    volumes:
      - './nginx/data:/etc/nginx'
      - './nginx/lua:/usr/local/openresty/nginx/lua'
    networks:
      - front-tier
      - back-tier
    depends_on:
      - users

  pwa:
    build:
      context: ./../pwa
      dockerfile: Dockerfile
    restart: always
    image: danydodson/seesee-pwa
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:8081
    stdin_open: true
    volumes:
      - './../pwa:/usr/src/app'
      - 'pwa-nm:/usr/src/app/node_modules'
    networks:
      - front-tier
    depends_on:
      - users

  users:
    build:
      context: users
      dockerfile: Dockerfile
    restart: always
    image: danydodson/seesee-users
    volumes:
      - './users:/usr/src/app'
      - 'users-nm:/usr/src/app/node_modules'
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: npm run debug
    networks:
      - back-tier

networks:
  front-tier:
  back-tier:

volumes:
  pwa-nm: null
  users-nm: null
